stages:
    - build
    - deploy

variables:
  IMAGE_JS: js
  CONTAINER_RELEASE_JS: docker-registry.web.innovation.insee.test/bootcampjs/spoc-js/js:latest

package-js-prod:
  stage: build
  tags:
    - maven
  script:
    - 'yarn config set cache-folder /mnt/mesos/sandbox/yarnrepo'
    - 'yarn install'
    - 'yarn run build'
    - 'docker build -t $CONTAINER_RELEASE_JS .'
    - 'docker push $CONTAINER_RELEASE_JS'
  only:
    - master@bootcampjs/spoc-js


deploy:
  stage: deploy
  only:
    - master@innovation/bootcampjs/spoc-js
  tags:
    - maven
  script:
    - 'APP_ID=`cat marathon.json | jq .id -r`'
    - 'curl -d@marathon.json -H "Content-Type: application/json" -X PUT http://marathon.mesos:8080/v2/apps/$APP_ID?force=true'
  environment:
    name: prod
    url: https://spoc-js.web.innovation.insee.test
